# Generated by Django 4.2.22 on 2025-06-06 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RegistroEstacionamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("placa", models.CharField(max_length=7)),
                ("estado", models.CharField(blank=True, max_length=50)),
                ("entrada", models.DateTimeField()),
                ("saida", models.DateTimeField()),
                ("valor_pago", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
