# Generated by Django 4.2.22 on 2025-06-06 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registroestacionamento",
            name="entrada",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="registroestacionamento",
            name="saida",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
